services:
  - type: web
    name: pigmy-collection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: pigmy-collection-db
          property: connectionString
      - key: SESSION_COOKIE_SECURE
        value: "true"
databases:
  - name: pigmy-collection-db
    plan: free
